# Generated by Django 5.2.6 on 2025-12-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatoEntrenamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuente_url",
                    models.URLField(blank=True, verbose_name="URL de origen"),
                ),
                ("consulta", models.TextField(verbose_name="Consulta")),
                ("contenido_raw", models.TextField(verbose_name="Contenido crudo")),
                (
                    "features",
                    models.JSONField(default=dict, verbose_name="Features extraídas"),
                ),
                (
                    "categoria_equipo",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Eléctrico"),
                            (2, "Hidráulico"),
                            (4, "Mecánico"),
                            (8, "General"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (100, "Alta"),
                            (50, "Media"),
                            (10, "Baja"),
                            (999, "Crítica"),
                        ],
                        null=True,
                    ),
                ),
                ("usado_entrenamiento", models.BooleanField(default=False)),
                ("conjunto", models.CharField(blank=True, max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dato de Entrenamiento",
                "verbose_name_plural": "Datos de Entrenamiento",
                "db_table": "dato_entrenamiento",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del equipo"),
                ),
                (
                    "empresa_nombre",
                    models.CharField(max_length=100, verbose_name="Empresa"),
                ),
                (
                    "categoria",
                    models.IntegerField(
                        choices=[
                            (1, "Eléctrico"),
                            (2, "Hidráulico"),
                            (4, "Mecánico"),
                            (8, "General"),
                        ],
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "es_critico",
                    models.BooleanField(default=False, verbose_name="¿Es crítico?"),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de serie"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=200, verbose_name="Ubicación"),
                ),
                (
                    "estado",
                    models.CharField(
                        default="operativo", max_length=20, verbose_name="Estado"
                    ),
                ),
                (
                    "metadatos",
                    models.JSONField(
                        default=dict, verbose_name="Metadatos adicionales"
                    ),
                ),
                (
                    "fecha_instalacion",
                    models.DateTimeField(verbose_name="Fecha de instalación"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "db_table": "equipo",
                "ordering": ["-es_critico", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ModeloIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del modelo"),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Versión")),
                (
                    "hiperparametros",
                    models.JSONField(default=dict, verbose_name="Hiperparámetros"),
                ),
                (
                    "estado",
                    models.CharField(
                        default="idle", max_length=20, verbose_name="Estado"
                    ),
                ),
                (
                    "precision_actual",
                    models.FloatField(default=0.0, verbose_name="Precisión actual"),
                ),
                (
                    "datos_entrenamiento",
                    models.IntegerField(
                        default=0, verbose_name="Datos de entrenamiento"
                    ),
                ),
                (
                    "epocas_completadas",
                    models.IntegerField(default=0, verbose_name="Épocas completadas"),
                ),
                (
                    "historial_metricas",
                    models.JSONField(
                        default=list, verbose_name="Historial de métricas"
                    ),
                ),
                (
                    "fecha_ultimo_entrenamiento",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "modelo_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Path del modelo"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Modelo de IA",
                "verbose_name_plural": "Modelos de IA",
                "db_table": "modelo_ia",
                "ordering": ["-activo", "-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tecnico", "Técnico"),
                            ("repuesto", "Repuesto"),
                            ("proveedor", "Proveedor"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de recurso",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "especialidad",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Especialidad"
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(default=0, verbose_name="Stock disponible"),
                ),
                (
                    "stock_minimo",
                    models.IntegerField(default=0, verbose_name="Stock mínimo"),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contacto"
                    ),
                ),
                (
                    "disponible",
                    models.BooleanField(default=True, verbose_name="¿Disponible?"),
                ),
                (
                    "calificacion",
                    models.FloatField(default=5.0, verbose_name="Calificación"),
                ),
                ("metadatos", models.JSONField(default=dict, verbose_name="Metadatos")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "db_table": "recurso",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("incidente", "Incidente"),
                            ("telemetria", "Telemetría IoT"),
                            ("flujo", "Flujo de Proceso"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "severidad",
                    models.IntegerField(default=5, verbose_name="Severidad (1-10)"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "datos",
                    models.JSONField(default=dict, verbose_name="Datos del evento"),
                ),
                (
                    "resuelto",
                    models.BooleanField(default=False, verbose_name="¿Resuelto?"),
                ),
                (
                    "fecha_evento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del evento"
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="api.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "evento",
                "ordering": ["-severidad", "-fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preventivo", "Mantenimiento Preventivo"),
                            ("correctivo", "Mantenimiento Correctivo"),
                            ("inspeccion", "Inspección"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        choices=[
                            (100, "Alta"),
                            (50, "Media"),
                            (10, "Baja"),
                            (999, "Crítica"),
                        ],
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.IntegerField(
                        choices=[
                            (1, "Pendiente"),
                            (2, "En Progreso"),
                            (4, "Completado"),
                            (8, "Cancelado"),
                        ],
                        default=1,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "tecnico_asignado",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Técnico"
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(verbose_name="Fecha programada"),
                ),
                (
                    "fecha_completada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha completada"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                ("resultado", models.TextField(blank=True, verbose_name="Resultado")),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Costo"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenimientos",
                        to="api.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
                "db_table": "mantenimiento",
                "ordering": ["-prioridad", "fecha_programada"],
            },
        ),
    ]
