# Generated by Django 5.2.6 on 2025-12-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ELECTRICO", "Eléctrico"),
                    ("HIDRAULICO", "Hidráulico"),
                    ("MECANICO", "Mecánico"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="prioridad",
            field=models.CharField(
                choices=[("ALTA", "Alta"), ("MEDIA", "Media"), ("BAJA", "Baja")],
                default="MEDIA",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="especialidad",
            field=models.CharField(
                choices=[
                    ("ELECTRICO", "Eléctrico"),
                    ("HIDRAULICO", "Hidráulico"),
                    ("MECANICO", "Mecánico"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
